### ISSUE TITLE
Weather - Current Location

### ISSUE THREAD

**Issue by ChaseHamby** [nss-evening-cohort-8/nutshell-betels#7]
# User Story
On page load, user should be able to see the weather for the site location (ex: Houston). 

# Dev Notes
• On page load, there will be a API call on a predetermined location (Houston)

# Acceptance Criteria
On page load, I should see a weather section on the page that displays the weather conditions for my pre-set location (Houston).

**Comment by marshalloffutt** [comment]
To close this ticket I still need to:

1. Edit and rename JSON file seed data for each user. Instead of 'weather1', 'weather2', etc it will be 'location1', 'location'2, so as to not get it confused with my weatherGetter from weatherbit api.
2. Update my initialize weather function, get rid of the zipcode test.
3. Write function for zipcode getter in weatherData. This function will get the data from JSON file.
4. Write function to print IsCurrent location to the home page.

**Comment by marshalloffutt** [comment]
weatherData.js <-- getAllLocations function

const getAllLocations = () => new Promise((resolve, reject) => {
  axios.get(`${firebaseUrl}/locations.json`)
    .then((results) => {
      const locationsObject = results.data;
      const locationsArray = [];
      if (locationsObject !== null) {
        Object.keys(locationsObject).forEach((locationId) => {
          locationsObject[locationId].id = locationId;
          locationsArray.push(locationsObject[locationId]);
        });
      }
      resolve(locationsArray);
    })
    .catch((error) => {
      reject(error);
    });
});

**Comment by marshalloffutt** [comment]
Apply the following id's for the weatherSection function to place data into via stringbuilder function:

wea-city
wea-desc
wea-img
wea-temp
wea-perc
wea-hum
wea-wind

```
<h4 class="card-title city-state" id="wea-city"></h4>
<h5 class="card-subtitle mb-2 text-muted weather-desc" id="wea-desc"></h5>
<img class="card-img weather-icon" id="wea-img" src=""></img>
<h4 class="card-title" id="wea-temp"></h4>
<p class="card-text" id="wea-perc"></p>
<p class="card-text" id="wea-hum"></p>
<p class="card-text" id="wea-wind"></p>
```

**Comment by marshalloffutt** [comment]
initializeWeatherWidget = () => {
weatherPage();
bindEvents();
}

**Comment by marshalloffutt** [comment]
const weatherPage = () => {
locationsData.getAllLocations()
.then((locationsArray) => {
printWeatherFromLocation(locationsArray)
