### ISSUE TITLE
Weather - Add Location

### ISSUE THREAD

**Issue by ChaseHamby** [nss-evening-cohort-8/nutshell-betels#9]
# User Story
As a user, I should see an input field for Zip Code. Once I enter the zip code, and press enter, it will populate a form that will already have the data from the API call. I should then have the option to click a "Add Location" or "Save Location" button that will add the location my dropdown location list. 

# Dev Notes
• Build a function that upon entering the zip code information, it will trigger the API call to get the data, and it will trigger a form builder. 

# Acceptance Criteria
I should be able to enter in a zip code in an input field and once I hit enter, it should pop up a form. In that form, it should have the data from the API call for that zip code. I can then hit a save location button and it will add it to the dropdown list. 

Given a user wants to add a weather location
When the user clicks an affordance for entering a new location (i.e. button or hyperlink)
Then a form should be presented to the user with a field to enter in the location zipcode and the user should have an affordance for if the location is the current location (i.e. checkbox)
And then the user should see the weather for the current location on the dashboard

**Comment by marshalloffutt** [comment]
getting location from input fields

```
const gettingLocationFromInputFields = () => {
  const location = {
    zipcode: $('#zipCodeInputField').val(),
    city_name: $('#cityInputField').val(),
    isCurrent: false,
  };
  return location;
};
```

**Comment by marshalloffutt** [comment]
weatherCrud: addNewLocation

```
const addNewLocation = () => {
  const newLocation = gettingTaskFromInputFields();
  locationsData.addNewLocation(newLocation);
    .then(() => {
      weatherCrap.initializeWeather();
    })
    .catch((error) => {
      console.error('error', error);
    });
};

```

**Comment by marshalloffutt** [comment]
locationsData: addNewLocationAxios

```
const addNewLocationAxios = locationObject => axios.post(`${firebaseUrl}/locations.json`, JSON.stringify(locationObject));
```
